
q1: 
	
	gcc -o q1.out q1.c
	@echo "=> Running compiled file \n"
	./q1.out

q2:
	
	gcc -o q2.out q2.c
	@echo "=> Running compiled file \n"
	./q2.out

q3:
	
	gcc -o q3.out q3.c
	@echo "=> Running compiled file \n"
	./q3.out

q4:
	
	gcc -o q4.out q4.c
	@echo "=> Running compiled file \n"
	./q4.out

q5:

	gcc -o q5.out q5.c
	@echo "=> Running compiled file \n"
	./q5.out
run_q6:
	gcc -o q6.out q6.c
	@echo "=> Running compiled file \n"
	./q6.out

clear:
	@echo "=> Clearing all compiled files"
	rm  q1.out q2.out q3.out q4.out q5.out 
