compile:
	gcc -o q1.out q1.c
	gcc -o q2.out q2.c

run_q1: 
	@echo "=> Compiling file for q1"
	gcc -o q1.out q1.c
	@echo "=> Running compiled file"
	./q1.out
run_q2:
	@echo "=> Compiling file for q2"
	gcc -o q2.out q2.c
	@echo "=> Running compiled file /n /n"
	./q2.out
run_q3:
	@echo "=> Compiling file for q3"
	gcc -o q3.out q3.c
	@echo "=> Running compiled file \n \n"
	./q3.out
run_q4:
	@echo "=> Compiling file for q4"
	gcc -o q4.out q4.c
	@echo "=> Running compiled file \n \n"
	./q4.out
run_q5:
	@echo "=> Compiling file for q5"
	gcc -o q5.out q5.c
	@echo "=> Running compiled file \n \n"
	./q5.out
clear:
	@echo "=> Clearing all compiled files"
	rm  q1.out q2.out q3.out q4.out q5.out
