q3_01:
	@echo "=> Compiling file for q3_01"
	gcc -o q3_01.out q3_01.c
	@echo "=> Running compiled file \n \n"
	./q3_01.out

q3_02:
	@echo "=> Compiling file for q3_02"
	gcc -o q3_02.out q3_02.c
	@echo "=> Running compiled file \n \n"
	./q3_02.out

q4:
	@echo "=> Compiling file for q4"
	gcc -o q4.out q4.c
	@echo "=> Running compiled file \n"
	./q4.out

clear:
	@echo "=> Clearing all compiled files"
	rm  q3_01.out q3_02.out q4.out 



