q1: 	

	gcc -o q1.out q1.c
	@echo "=> Running compiled file \n"
	./q1.out

q2_01:
	
	gcc -o q2_01.out q2_01.c
	@echo "=> Running compiled file \n"
	./q2_01.out

q2_02:
	
	gcc -o q2_02.out q2_02.c
	@echo "=> Running compiled file \n"
	./q2_02.out

q2_03:
	
	gcc -o q2_03.out q2_03.c
	@echo "=> Running compiled file \n"
	./q2_03.out

q2_04:
	
	gcc -o q2_04.out q2_04.c
	@echo "=> Running compiled file \n"
	./q2_04.out

q3:
	
	gcc -o q3.out q3.c
	@echo "=> Running compiled file \n"
	./q3.out

q4:
	
	gcc -o q4.out q4.c
	@echo "=> Running compiled file \n"
	./q4.out

q5:

	gcc -o q5.out q5.c
	@echo "=> Running compiled file \n"
	./q5.out
run_q6:
	gcc -o q6.out q6.c
	@echo "=> Running compiled file \n"
	./q6.out

clear:
	@echo "=> Clearing all compiled files"
	rm  q1.out q2_01.out q2_02.out q2_03.out q2_04.out q3.out q5.out 
